server:
 error:
  include-stacktrace: on_trace_param

spring:
 datasource:
   url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
   username: root
   password: 123naldo
 jpa:
   hibernate:
    ddl-auto: update